{"name": "Проверка получения ошибки при создания курьера с логином, который уже есть", "status": "passed", "description": "Проверка, что в случае создания курьера с уже существующим логином приходит ошибка, а также в ответе сервера получены верный код и тело. По окончании теста тестовые данные удаляются", "start": 1722541537235, "stop": 1722541537879, "uuid": "f09df340-8040-42ae-8f27-eff8f4505efd", "historyId": "93e6466d9a80d620f56414eaa1c06930", "testCaseId": "93e6466d9a80d620f56414eaa1c06930", "fullName": "tests.test_create_courier.TestsCreateCourier#test_create_courier_with_existing_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestsCreateCourier"}, {"name": "host", "value": "DESKTOP-LJDD8TD"}, {"name": "thread", "value": "8712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}