{"name": "Проверка получения ошибки при авторизации курьера с неправильно указанным паролем", "status": "passed", "description": "Проверка, что в случае отправки запроса авторизации с неверным паролем приходит ошибка, а также в ответе сервера получены верный код и тело.", "start": 1722541562810, "stop": 1722541562889, "uuid": "04e0c896-e22f-4c13-85f1-a2c6dd45055f", "historyId": "c1143a0c3833717da91ab3caf835cd79", "testCaseId": "c1143a0c3833717da91ab3caf835cd79", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_not_authorized_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-LJDD8TD"}, {"name": "thread", "value": "8712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}