{"name": "Проверка получения ошибки при авторизации курьера с неправильно указанным логином", "status": "passed", "description": "Проверка, что в случае отправки запроса авторизации с неверным логином приходит ошибка, а также в ответе сервера получены верный код и тело.", "start": 1722541562731, "stop": 1722541562807, "uuid": "3b272cea-80d1-41c4-bb2e-632245ffd703", "historyId": "bf2625d82f96c0ffc78db6b9b7d62d44", "testCaseId": "bf2625d82f96c0ffc78db6b9b7d62d44", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_not_authorized_with_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-LJDD8TD"}, {"name": "thread", "value": "8712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}